# Generated by Django 5.1.4 on 2026-05-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='configured_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='selected_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='client_uploads'),
        ),
    ]
