# Generated by Django 5.1.4 on 2026-05-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='selected_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='order_uploads'),
        ),
    ]
