# Generated by Django 5.1.4 on 2026-05-17 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=180)),
                ('contact_name', models.CharField(max_length=180)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=60)),
                ('product_type', models.CharField(max_length=120)),
                ('desired_quantity', models.PositiveIntegerField()),
                ('desired_deadline', models.CharField(max_length=120)),
                ('estimated_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('message', models.TextField()),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='quote_uploads')),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('analyzing', 'En analyse'), ('sent', 'Devis envoye'), ('accepted', 'Accepte'), ('refused', 'Refuse'), ('archived', 'Archive')], default='new', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
