# Generated by Django 5.1.4 on 2026-05-16 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(max_length=80)),
                ('input_type', models.CharField(choices=[('select', 'Liste de choix'), ('text', 'Texte libre'), ('file', 'Upload fichier')], default='select', max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('help_text', models.CharField(blank=True, max_length=250)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'unique_together': {('product', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ProductOptionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('value', models.SlugField(max_length=80)),
                ('price_delta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='products.productoption')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'unique_together': {('option', 'value')},
            },
        ),
    ]
